---
- name: crear snapshots en vms canales
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - rhev_login_password.yml
    - rhev_login_vars.yml
    - rhev_lista_vms.yml
  
  vars: 
  - hoy: "{{ fecha_hoy.stdout }}"
  
  pre_tasks:
  - name: Login a rhev
    ovirt_auth:
      username: "{{ rhev_user }}"
      password: "{{ rhev_pass }}"
      url: "{{ rhev_url }}"
      ca_file: "{{ rhev_cert }}"
    tags:
      - always

  tasks:
  - name: timestamp de hoy
    command: date +%Y%m%d
    register: fecha_hoy

  - name: Crear snapshot
    ovirt_snapshot:
      auth: "{{ ovirt_auth }}"
      description: "snap_prueba_{{ hoy }}"
      vm_name: "openshift01"
      state: "present"
      wait: "yes"
    register: snapshot

  - name: Borrar snapshot
    ovirt_snapshot:
      auth: "{{ ovirt_auth }}"
      vm_name: "openshift01"
      keep_days_old: 1

  